name: cd sistoko fe
on: 
  push:
    branches: [main]
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.168.1.9 # Your server's IP address
          username: donihadimas # Your server's username
          password: ${{ secrets.PRIVATE_KEY }} # Your server's SSH private key
          script: |
            cd /root/workspace/project/sistoko/sistoko-fe-nextjs
            git pull origin main
            npm install --force
            npm run build
            pm2 restart sistoko-fe-nextjs
