name: cd sistoko fe
on: 
  push:
    branches: [main]
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@0.1.4
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key
          script: |
            cd /root/workspace/project/sistoko/sistoko-fe-nextjs
            git pull origin main
            npm install --force
            npm run build
            pm2 restart sistoko-fe-nextjs
