name: cd sistoko fe
on: 
  push:
    branches: [main]
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          script: |
            cd /root/workspace/project/sistoko/sistoko-fe-nextjs
            git pull origin main
            npm install --force
            npm run build
            pm2 restart sistoko-fe-nextjs
